config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  resources :scores

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/me', to: 'me#index'
  get '/me/edit', to: 'me#edit'
  put '/me/edit', to: 'me#update'
  get '/me/token', to: 'token#index'
  put '/me/token', to: 'token#update'

  root to: 'scores#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  with_options presence: true do
    validates :wakeup_on
    validates :score
    validates :reason
  end
  with_options length: { maximum: 50 } do
    validates :reason
    validates :cause
  end

  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :scores, dependent: :nullify

  def initialize(*)
    super
    self.token ||= SecureRandom.alphanumeric(20)
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth[:uid], provider: auth[:provider]).first
    user ||= User.create(
      provider: auth[:provider],
      uid: auth[:uid],
      name: auth[:info][:name],
      t_username: auth[:info][:nickname],
      email: User.dummy_email(auth),
      admin: false,
      password: Devise.friendly_token[0, 20]
    )
    user
  end

  private

  def self.dummy_email(auth)
    "#{auth[:uid]}@#{auth[:provider]}.com"
  end

end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :reqire_admin
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "#{@user.name} を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path(@user), notice: "#{@user.name} を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "#{@user.name} を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password)
  end

  def reqire_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= find_user
  end

  def find_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    elsif request.headers['X-Feel-So-Good-Authorization']
      User.find_by(token: request.headers['X-Feel-So-Good-Authorization'])
    end
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/me_controller.rb
# frozen_string_literal: true

class MeController < ApplicationController
  def index
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(me_params)
      redirect_to me_path, notice: "#{@user.name} を更新しました。"
    else
      render :edit
    end
  end

  private

  def me_params
    params.permit(:name, :email, :password)
  end
end

app/controllers/scores_controller.rb
# frozen_string_literal: true

class ScoresController < ApplicationController
  def index
    @scores = current_user.scores.order(wakeup_on: :desc)
    @labels, @dataset = get_labels(current_user.scores.order(wakeup_on: :asc))
  end

  def show
    @score = current_user.scores.find(params[:id])
  end

  def new
    @score = Score.new
  end

  def create
    @score = current_user.scores.new(score_params)
    if @score.save
      redirect_to @score, notice: "#{@score.wakeup_on} の気分を登録しました。"
    else
      render :new
    end
  end

  def edit
    @score = current_user.scores.find(params[:id])
  end

  def update
    @score = current_user.scores.find(params[:id])
    if @score.update(score_params)
      redirect_to @score, notice: "#{@score.wakeup_on} の気分を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    score = current_user.scores.find(params[:id])
    score.destroy
    redirect_to scores_url, notice: "#{score.wakeup_on} の気分を削除しました。"
  end

  private

  def score_params
    params.require(:score).permit(:wakeup_on, :score, :reason, :cause)
  end

  def get_labels(scores)
    labels = []
    dataset = []
    scores.each do |score|
      labels.push(score.wakeup_on)
      dataset.push(score.score)
    end
    [labels.slice(0, 30).to_json.html_safe, dataset.slice(0, 30)]
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create omniauth]

  def new
    reset_session
    @is_twitter = ENV['TWITTER_ENABLED']
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      flash.now[:alert] = 'ID かパスワードが違います。'
      render :new
    end
  end

  def omniauth
    user = User.find_for_oauth(request.env['omniauth.auth'])
    if user.persisted?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ユーザー認証が完了しました。'
    else
      flash.now[:alert] = 'ユーザー認証に失敗しました。'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/token_controller.rb
# frozen_string_literal: true

class TokenController < ApplicationController
  def index
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(token: SecureRandom.alphanumeric(20))
      redirect_to me_token_path, notice: 'API Token を更新しました。'
    else
      render :edit
    end
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin
  module UsersHelper
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/me_helper.rb
# frozen_string_literal: true

module MeHelper
end

app/helpers/scores_helper.rb
# frozen_string_literal: true

module ScoresHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/token_helper.rb
# frozen_string_literal: true

module TokenHelper
end

app/views/admin/tokens/show.html.slim
h1 API Token の更新

= form_with url: admin_user_token_path, method: :put, local: true do |f|
  .form-group
    = f.label :token, 'API Token'
    = f.text_field :token, class: 'form-control', id: 'users_token', disabled: true, value: @user.token
  .btn-toolbar
    .btn-group.mr-2
      = link_to 'キャンセル', edit_admin_user_path(@user), class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = button_tag type: 'submit', class: 'btn btn-primary' do
        i.fa.fa-refresh
        |  更新する

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message



= form_with model: [:admin, @user], local: true do |f|
  .form-group
    = f.label :name, 'Name'
    = f.text_field :name, class: 'form-control', id: 'user_name', required: true
  .form-group
    = f.label :email, 'E-mail'
    = f.text_field :email, class: 'form-control', required: true
  .form-group
    .form-check
      = f.label :admin, class: 'form-check-label' do
        = f.check_box :admin, class: 'form-check-input'
        | Administrator
  .form-group
    = f.label :password, 'Password'
    = f.password_field :password, class: 'form-control', required: true
  .btn-toolbar
    .btn-group.mr-2
      = link_to 'キャンセル', admin_users_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = f.submit '保存する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
- breadcrumb :edit_user, @user

h1 ユーザーの編集

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
- breadcrumb :users

h1 ユーザー一覧

.nav.justify-content-end
  = link_to (fa_icon 'plus'), new_admin_user_path, class: 'btn btn-outline-primary'

.mb-3
table.table.table-hover
  thead.thead-light
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.admin? ? 'あり' : 'なし'
        td= user.created_at
        td= user.updated_at
        td
          .btn-toolbar.justify-content-end
            .btn-group.mr-2
              = link_to (fa_icon 'pencil'), edit_admin_user_path(user), class: 'btn btn-primary btn-primary'
            .btn-group.mr-2
              = link_to (fa_icon 'trash-o'), [:admin, user], method: :delete, data: { confirm: "#{user.name} を削除します。よろしいですか？" }, class: 'btn btn-danger btn-danger'

app/views/admin/users/new.html.slim
- breadcrumb :new_user

h1 ユーザーの登録

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
- breadcrumb :show_user, @user

h1 ユーザーの詳細

.nav.justify-content-end
  .btn-toolbar.toolbar
    .btn-group.mr-2
      = link_to (fa_icon 'plus'), new_admin_user_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = link_to (fa_icon 'pencil'), edit_admin_user_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = link_to (fa_icon 'trash-o'), [:admin, @user], method: :delete, data: { confirm: "#{@user.name} を削除します。よろしいですか？" }, class: 'btn btn-outline-danger'


table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name='viewport' content='width=device-width, initial-scale=1'
    title
      | feel-so-good
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag()
  body
    .app-title.navbar.navbar-expand-lg.navbar-dark.bg-primary
      .navbar-brand
        i.fa.fa-heart
        |  feel-so-good
      button.navbar-toggler.navbar-toggler-right data-toggle='collapse' data-target='#menu' aria-controls='menu' aria-expanded='false' aria-label='Toggle navigation'
        span.navbar-toggler-icon

      #menu.collapse.navbar-collapse
        ul.navbar-nav.ml-auto
          - if current_user
            li.nav-item.active= link_to (fa_icon 'heart', text: ' 気分スコア'), scores_path, class: 'nav-link'
            li.nav-item= link_to (fa_icon 'user ', text: ' ユーザー情報'), me_path, class: 'nav-link'
            - if current_user.admin?
              li.nav-item= link_to (fa_icon 'users ', text: ' ユーザー管理'), admin_users_path, class: 'nav-link'
            li.nav-item= link_to (fa_icon 'sign-out', text: ' ログアウト'), logout_path, method: :delete, class: 'nav-link'
          - else
            li.nav-item= link_to (fa_icon 'sign-in', text: ' ログイン'), login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success.alert-dismissible.fade.show
          = flash.notice
          button.close type='button' data-dismiss='alert' aria-label='閉じる'
            span aria-hidden='true' &times;
      - if flash.alert.present?
        .alert.alert-danger.alert-dismissible.fade.show
          = flash.alert
          button.close type='button' data-dismiss='alert' aria-label='閉じる'
            span aria-hidden='true' &times;
      breadcrumb
        == breadcrumbs style: :bootstrap, semantic: true, separator: '&nbsp;&rsaquo;&nbsp;', class: 'breadcrumb bg-light'
      = yield

app/views/me/edit.html.slim
- breadcrumb :edit_me, @user

h1 ユーザーの編集

- if @user.errors.present?
  ul#error_explanation
    - score.errors.full_messages.each do |message|
      li= message

= form_with url: me_edit_path, method: :put, local: true do |f|
  .form-group
    = f.label :name, 'Name'
    = f.text_field :name, value: @user.name, class: 'form-control', id: 'user_name', required: true
  .form-group
    = f.label :email, 'E-mail'
    = f.text_field :email, value: @user.email, class: 'form-control', required: true
  .form-group
    = f.label :password, 'Password'
    = f.password_field :password, class: 'form-control', required: true
  .form-group
    = link_to 'API Token', me_token_path, class: 'pull-right'
  .btn-toolbar
    .btn-group.mr-2
      = link_to 'キャンセル', me_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = f.submit '保存する', class: 'btn btn-primary'

app/views/me/index.html.slim
- breadcrumb :me, @user

h1 ユーザーの詳細

.nav.justify-content-end
  .btn-toolbar.toolbar
    .btn-group.mr-2
      = link_to (fa_icon 'pencil'), me_edit_path, class: 'btn btn-outline-primary'

table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

app/views/scores/_form.html.slim
- if score.errors.present?
  ul#error_explanation
    - score.errors.full_messages.each do |message|
      li= message

= form_with model: score, local: true do |f|
  .form-group
    = f.label :date
    = f.text_field :wakeup_on, class: 'form-control datetimepicker-input', id: 'score_date', type: "date", value: (@score.persisted? ? @score.wakeup_on : DateTime.now.strftime('%Y-%m-%d')), required: true
  .form-group
    = f.label :score
    .col-xs-9
    - (-5..5).each do |i|
      .form-check-inline
        = f.radio_button :score, i, class: 'form-check-input', id: "score_score-#{i}", checked: (@score.persisted? ? i == @score.score : i == 0)
        = f.label "score_score-#{i}", i, class: 'form-check-label'
  .form-group
    = f.label :reason
    = f.text_field :reason, class: 'form-control', id: 'score_reason', required: true
  .form-group
    = f.label :cause
    = f.text_field :cause, class: 'form-control', id: 'score_cause'
  .btn-toolbar
    .btn-group.mr-2
      = link_to 'キャンセル', scores_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = f.submit '保存する', class: 'btn btn-primary'

app/views/scores/edit.html.slim
- breadcrumb :edit_score, @score

h1 スコアの編集

= render partial: 'form', locals: { score: @score }

app/views/scores/index.html.slim
- breadcrumb :scores

h1 気分スコア一覧

canvas id="chart"
javascript:
  if (document.readyState === "complete") {
    drawChart();
  } else {
    document.addEventListener("DOMContentLoaded", drawChart);
  }
  function drawChart(){
    var ctx = document.getElementById('chart').getContext('2d');
    ctx.canvas.height = 150;
    var chart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: #{@labels},
        datasets: [{
          label: 'Score',
          data: #{@dataset},
          backgroundColor: '#6cc3d5',
          borderColor: '#6cc3d5',
          fill: false
        }]
      },
      options: {
        responsive: true,
        legend: {
          display: false
        },
        scales: {
          xAxes: [{
             ticks: {
               fontSize: 8
             }
          }],
          yAxes: [{
            ticks: {
               fontSize: 8,
              beginAtZero: false,
              min: -5,
              max: 5,
              stepSize: 1
            },
            gridLines: {
              borderDash: [3,5]
            }
          }]
        }
      }
    });
  };

.nav.justify-content-end
  = link_to (fa_icon 'plus'), new_score_path, class: 'btn btn-outline-primary'

.mb-3
table.table.table-hover
  thead.thead-light
    tr
      th= Score.human_attribute_name(:wakeup_on)
      th= Score.human_attribute_name(:score)
      th= Score.human_attribute_name(:reason)
      th= Score.human_attribute_name(:cause)
      th
  tbody
    - @scores.each do |score|
      tr
        td= link_to score.wakeup_on, score
        td= score.score
        td= score.reason
        td= score.cause
        td
          .btn-toolbar.justify-content-end
            .btn-group.mr-2
              = link_to (fa_icon 'pencil'), edit_score_path(score), class: 'btn btn-primary'
            .btn-group.mr-2
              = link_to (fa_icon 'trash-o'), score, method: :delete, data: { confirm: "#{score.wakeup_on} の気分を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/scores/new.html.slim
- breadcrumb :new_score

h1 スコアの新規登録

= render partial: 'form', locals: { score: @score }

app/views/scores/show.html.slim
- breadcrumb :show_score, @score

h1 気分の詳細

.nav.justify-content-end
  .btn-toolbar.toolbar
    .btn-group.mr-2
      = link_to (fa_icon 'plus'), new_score_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = link_to (fa_icon 'pencil'), edit_score_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
       = link_to (fa_icon 'trash-o'), @score, method: :delete, data: { confirm: "#{@score.wakeup_on} の気分を削除します。よろしいですか？" }, class: 'btn btn-outline-danger'

table.table.table-hover
  tbody
    tr
      th= Score.human_attribute_name(:wakeup_on)
      td= @score.wakeup_on
    tr
      th= Score.human_attribute_name(:score)
      td= @score.score
    tr
      th= Score.human_attribute_name(:reason)
      td= @score.reason
    tr
      th= Score.human_attribute_name(:cause)
      td= @score.cause
    tr
      th= Score.human_attribute_name(:created_at)
      td= @score.created_at
    tr
      th= Score.human_attribute_name(:updated_at)
      td= @score.updated_at

app/views/token/index.html.slim
- breadcrumb :token, @user

h1 API Token の更新

= form_with url: me_token_path, method: :put, local: true do |f|
  .form-group
    = f.label :token, 'API Token'
    = f.text_field :token, class: 'form-control', id: 'users_token', disabled: true, value: @user.token
  .btn-toolbar
    .btn-group.mr-2
      = link_to 'キャンセル', me_path, class: 'btn btn-outline-primary'
    .btn-group.mr-2
      = button_tag type: 'submit', class: 'btn btn-primary' do
        i.fa.fa-refresh
        |  更新する